### ISSUE TITLE
Kasowanie dysków chroot

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/packer#3]
Dysk służący dla chroot nie jest poprawnie czyszczony w przypadku zakończenia operacji błędem.

**Comment by m110** [comment]
@ad-m Jakiego stanu spodziewałbyś się w przypadku błędu? Jego zawartość będzie zależeć od operacji, które użytkownik wykona w `post_mount_actions`. Być może błędem jest, że dysk tymczasowy nie jest po prostu usuwany w pewnych przypadkach?

**Comment by ad-m** [comment]
@m110 , w przypadku błędu np. w momencie wykonania ```pre_mount_commands``` spodziewam się, że skoro jest usuwana wirtualna maszyna z dyskiem systemowym to zostanie także usunięty dysk. W momencie błędu w ```pre_mount_commands``` uważam, że nie powinien pozostawać żaden dysk.

Nieprecyzyjnie napisałem "poprawnie czyszczony" (cleanup), gdy powinno być "kasowany".
