### ISSUE TITLE
Wykrywanie dysku

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/packer#6]
W celu poprawnego wykrywania dysku możemy wykorzystać dane dostępne na:
```
h1 vm disk list --vm ...
```
Dostępne są tam:
- typ kontrolera,
- identyfikator kontrolera,
- pozycja w kontrolerze

Przykładowo:
```
 $ h1 vm disk list --vm 5c546a83f2306ddb9ada24a8
ID                                             IOPS  DISKNAME                                       DISKID                    DISKNAME                                       DISKTYPE  DISKSIZE
IDE/0/0                                        0     packer-5c530ff0-bd94-1870-8fcb-d695f1fe66b7 0  5c546a83f2306ddb9ada24aa  packer-5c530ff0-bd94-1870-8fcb-d695f1fe66b7 0  ssd       10
SCSI/{858D30B0-AAA6-42F7-BC69-11B6A958832A}/0  0     packer-chroot-disk                             5c546a83f2306ddb9ada24ae  packer-chroot-disk                             ssd       2
```

Dane te jednoznacznie identyfikują dysk. Wykorzystujemy kontroler IDE i SCSI. W przyszłości będziemy wykorzystywać co najwyżej 1 kontroler SCSI i prawdopodobnie zrezygnujemy z kontrolera IDE.

Nie możemy wykorzystać:
```
ls -lah /dev/disk/by-id/scsi-*    
```
gdyż - z naszej strony - wartość jest ustawiana zgodnie z ObjectId *Dysku*. Jednak po drodze coś zmienia ten identyfikator. Widać to po tym, że ostatnie znaki zgadzają się. 

Możemy wykorzystać dopasowanie na podstawie identyfikatora kontrolera i pozycji w kontrolerze. To są także dane jednoznaczne. Odpowiednie dane są widoczne w systemie w ```/sys/bus/vmbus/devices/858d30b0-aaa6-42f7-bc69-11b6a958832a/``` oraz przede wszystkim w ```/dev/disk/by-path/```:

```
$ ls -lah /dev/disk/by-path/*
lrwxrwxrwx. 1 root root  9 Feb  1 15:51 /dev/disk/by-path/acpi-VMBUS:01-scsi-0:0:0:0 -> ../../sdb
lrwxrwxrwx. 1 root root 10 Feb  1 15:51 /dev/disk/by-path/acpi-VMBUS:01-scsi-0:0:0:0-part1 -> ../../sdb1
lrwxrwxrwx. 1 root root 10 Feb  1 15:51 /dev/disk/by-path/acpi-VMBUS:01-scsi-0:0:0:0-part2 -> ../../sdb2
lrwxrwxrwx. 1 root root 10 Feb  1 15:51 /dev/disk/by-path/acpi-VMBUS:01-scsi-0:0:0:0-part3 -> ../../sdb3
lrwxrwxrwx. 1 root root  9 Feb  1 15:51 /dev/disk/by-path/pci-0000:00:07.1-ata-2 -> ../../sr0
```

**Comment by ad-m** [comment]
Prześledziłem kto dostarcza ```by-path``` w aktualnych systemach operacyjnych. Pochodzi to z reguł udev. Udev ma kilka implementacji, znaczące jest systemd i eudev. Aktualna wersja eudev importuje reguły z systemd. Zatem aktualne wersje systemów operacyjnych dostarczają poprawnie ```by-path```. Możemy zaakceptować, że builder działa wyłącznie z aktualnymi systemami, bo system w builderze łatwo zmieniać.

Z tego względu proponuje zbudować ścieżkę przez ```by-path```. Jeżeli występuje z tym problem - zadzwoń do mnie, abyśmy zamknęli to zagadnienie i mogli iść już dalej.

Podejście Amazonu jest kuszące, a jednocześnie jest lepsze niż zahardkodowana wartość. Z zahardkodowaną wartością mieliśmy dużo negatywnych doświadczeń w dotychczasowym rozwiązaniu, stąd wolelibyśmy tego uniknąć i zwracamy uwagę na ten obszar. Jeżeli wystąpi problem z ```by-path``` możemy ostatecznie nim pójść.

**Comment by m110** [comment]
@ad-m Można zweryfikować.
